version: '3.4'

services:
  timestamp:
    image: freecodecamp/timestamp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
